[crate]
	bin = "ptr"
[deps]
	ffi = { git = "https://github.com/myfamilyorg/ffi" }
	result = { git = "https://github.com/myfamilyorg/result" }
	errors = { git = "https://github.com/myfamilyorg/errors" }
	raw = { git = "https://github.com/myfamilyorg/raw" }
	macros = { git = "https://github.com/myfamilyorg/macros" }
